Stat svc
albertleinsoo/java-explore-with-me pull request #3
Opened 2023-08-28 09:07 UTC by albertleinsoo

2023-08-29 05:25 UTC, alexache requested changes

2023-08-29 05:25 UTC, alexache commented on main-service/pom.xml
> +                <version>3.8.1</version>
Версии плагинов должны быть заданы в родительском модуле через pluginManagement

2023-08-29 05:25 UTC, alexache commented on stats-service/client/src/main/java/ru/practicum/StatsClient.java
> +    public ResponseEntity<List<RequestOutputDto>> getStats(String start,
Для чего здесь ResponseEntity? Проверять резалт код?

2023-08-29 05:25 UTC, alexache commented on stats-service/dto/pom.xml
> +                <version>3.8.1</version>
В родительский модуль

2023-08-29 05:25 UTC, alexache commented on stats-service/server/pom.xml
> +            <version>1.5.3.Final</version>
Версии библиотек нужно указывать в родительском модуле, через depenndencyManagement

2023-08-29 05:25 UTC, alexache commented on stats-service/server/pom.xml
> +                            <version>${lombok.version}</version>
Так и эту версию библиотеки, так и ту, что немного ниже

2023-08-29 05:25 UTC, alexache commented on stats-service/server/src/main/java/ru/practicum/controller/StatsController.java
> +    private final StatsServiceImpl statsService;
Зависимости указываются на интерфейсы, не реализации - то есть StatsService

2023-08-29 05:25 UTC, alexache commented on stats-service/server/src/main/java/ru/practicum/controller/StatsController.java
> +        statsService.addRequest(requestDto);
Логгирование в контроллерах пригодится

2023-08-29 05:25 UTC, alexache commented on stats-service/server/src/main/test/java/ru/practicum/StatsServiceTest.java
> +    RequestDto requestDto;
Модификаторы доступа полей

2023-08-29 05:25 UTC, alexache commented on stats-service/server/src/main/test/java/ru/practicum/StatsServiceTest.java
> +public class StatsServiceTest {
В дипломном проекте тесты опциональны

2023-08-29 22:18 UTC, albertleinsoo commented on stats-service/server/pom.xml
> +            <version>1.5.3.Final</version>
Как понял, это невозможно, так как maven-compiler-plugin не позволяет использовать dependencyManagement.
https://stackoverflow.com/questions/75256735/docker-compose-up-what-is-flags-difference-always-recreate-deps-vs-build
https://issues.apache.org/jira/browse/MCOMPILER-391

2023-08-29 22:25 UTC, albertleinsoo commented on stats-service/server/pom.xml
> +                            <version>${lombok.version}</version>
Аналогично комментарию выше. Maven при сборке выдаёт ошибку и просит обязательно указать версию.

2023-08-31 05:04 UTC, alexache commented on stats-service/client/src/main/java/ru/practicum/StatsClient.java
> +    public ResponseEntity<List<RequestOutputDto>> getStats(String start,
Это можно проверять внутри клиента, а вовне - это не очень интересная информация

2023-08-31 05:09 UTC, alexache approved these changes

2023-08-31 05:09 UTC, alexache commented on stats-service/server/pom.xml
> +            <version>1.5.3.Final</version>
Это обычная зависимость (не внутри компайлер плагина), как это применимо?

2023-08-31 19:11 UTC, merged