main_svc
albertleinsoo/java-explore-with-me pull request #4
Opened 2023-09-05 17:32 UTC by albertleinsoo

2023-09-07 06:41 UTC, alexache requested changes

2023-09-07 06:41 UTC, alexache commented on main-service/src/main/java/ru/practicum/event/controller/EventController.java
> +        return eventService.getAll(text, categories, paid, rangeStart, rangeEnd, onlyAvailable, from, size, sort, request);
Можно не передавать весь объект   HttpServletRequest целиком, а только нужные поля

2023-09-07 06:41 UTC, alexache commented on main-service/src/main/java/ru/practicum/event/dto/EventShortDto.java
> +    @Size(min = 20, max = 2000)
Это ДТО от сервиса к клиенту, а не наоборот?  Тогда зачем валидации?

2023-09-07 06:41 UTC, alexache commented on main-service/src/main/java/ru/practicum/event/model/Event.java
> +    private Long confirmedRequests = 0L;
Этого поля не должно быть - подтвержденные запросы хранятся в другой таблице

2023-09-07 06:41 UTC, alexache commented on main-service/src/main/java/ru/practicum/event/model/Event.java
> +    private Long views = 0L;
Количество просмотров тоже не должно храниться в данной таблице, а запрашиваться в сервисе статистики

2023-09-07 06:41 UTC, alexache commented on main-service/src/main/java/ru/practicum/request/service/RequestServiceImpl.java
> +            event.setConfirmedRequests(event.getConfirmedRequests() + 1);
Это лишние действия

2023-09-07 06:41 UTC, alexache commented on main-service/src/main/java/ru/practicum/request/service/RequestServiceImpl.java
> +        event.setConfirmedRequests(event.getConfirmedRequests() - 1);
лишние операции

2023-09-07 06:41 UTC, alexache commented on main-service/src/main/java/ru/practicum/request/service/RequestServiceImpl.java
> +        if (!requests.isEmpty()) {
Стрим мап отработает корректно и на пустом результате от репозитория

2023-09-07 06:41 UTC, alexache commented on main-service/src/main/java/ru/practicum/request/service/RequestServiceImpl.java
> +        for (ParticipationRequest request : participationRequests) {
(опционально) такие проверки хорошо ложатся на стримы и фильтры

2023-09-07 06:41 UTC, alexache commented on main-service/src/main/java/ru/practicum/request/service/RequestServiceImpl.java
> +            return new EventRequestStatusUpdateResult(
А сохранять в базу статус CONFIRMED?

2023-09-07 06:41 UTC, alexache commented on main-service/src/main/java/ru/practicum/request/service/RequestServiceImpl.java
> +                requestRepository.save(participationRequest);
Запросы к базе в цикле плохо, лучше после цикла сделать saveAll

2023-09-07 06:41 UTC, alexache commented on main-service/src/main/java/ru/practicum/request/service/RequestServiceImpl.java
> +            if (event.getConfirmedRequests() < event.getParticipantLimit()) {
Это понадобится отслеживать как нибудь иначе

2023-09-07 06:41 UTC, alexache commented on main-service/src/main/java/ru/practicum/user/controller/AdminUserController.java
> +    public UserDto addAdminUser(@RequestBody @Valid NewUserRequestDto newUserRequestDto) {
Название немного противоречивое - звучит как добавление админа

2023-09-07 06:41 UTC, alexache commented on main-service/src/main/java/ru/practicum/user/dto/UserShortDto.java
> +    @NotNull
Это звучит как выходная ДТО, на ней валидация не имеет смысла

2023-09-07 06:41 UTC, alexache commented on main-service/src/main/resources/schema.sql
> +    annotation VARCHAR NOT NULL,
Лучше для всех строковых столбцов указывать пределы, валидные по смыслу

2023-09-07 06:41 UTC, alexache commented on main-service/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +    private final StatsClient statsClient = new StatsClient("http://ewm-stats-server:9090");
Когда есть спринг, создавать вручную объекты выглядит неправильно

2023-09-07 06:41 UTC, alexache commented on main-service/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +        if (listResponseEntity.getStatusCode() == HttpStatus.OK &&
Это лишние действия

2023-09-13 19:07 UTC, albertleinsoo commented on main-service/src/main/java/ru/practicum/event/model/Event.java
> +    private Long views = 0L;
Сервис статистики отслеживает только переход по ендпоинтам. Но если был переход по ендпоинту /events , логичнее каждому Event, существующему на данный момент, увеличить просмотры. А если вычислять количество просмотров конкретного события из сервиса статистики, надо учитывать переходы по /event/{id} и /events. Однако, тогда может возникнуть ситуация: переход /events -> создание event {id=1} -> переход /event/2 ->  переход /events. У этого события должно быть 2 просмотра. Но при учёте ендпоинтов /events, мы получим 3 просмотра

2023-09-15 18:50 UTC, alexache commented on main-service/src/main/java/ru/practicum/event/model/Event.java
> +    private Long confirmedRequests = 0L;
Пострадает корректность данных и возрастает нагрузка на базу. Сложно сделать правильное и атомарное увеличение поля

2023-09-15 18:53 UTC, alexache commented on main-service/src/main/java/ru/practicum/event/model/Event.java
> +    private Long views = 0L;
Пострадает корректность данных и возрастает нагрузка на базу. Сложно сделать правильное и атомарное увеличение поля. Вся суть сервиса статистики выдавать эти данные основному сервису.

2023-09-15 19:07 UTC, alexache requested changes

2023-09-19 20:01 UTC, alexache requested changes

2023-09-19 20:01 UTC, alexache commented on main-service/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +        updateViews(requestAddress, requestUri);
Так же не вижу запросов для получения количества подтвержденных заявок событий

2023-09-21 17:54 UTC, alexache requested changes

2023-09-26 20:08 UTC, alexache commented on main-service/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +                .peek(eventShortDto -> eventShortDto.setViews(listResponseEntity.getBody() != null ? (long) listResponseEntity.getBody().size() : 0L))
Все равно не понимаю, что здесь происходит. У каждого ивента есть свой уникальный uri, на основе айди события, у сервиса статистики можно запросить статистику по списку таких уникальных uri, переложить в Мапу айди на количество просмотров, и успешно вернуть назад результат. Сейчас это немного странное число

2023-09-27 07:11 UTC, alexache commented on main-service/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +            statsClient.addRequest(requestDtoEvent);
Запрос к стороннему ресурсу в цикле запрещен, оставляй передачу статистики по базовой ссылке (не уникальной URI) и все

2023-09-27 07:11 UTC, alexache approved these changes

2023-09-27 12:18 UTC, merged